### ISSUE TITLE
Present Donate: 20171123 赞助 300元

### ISSUE THREAD

**Issue by Keith-CY** [Hangzhou-Node-Party/Node-OpenSource-Foundation#44]
杭州 node party 群, 微信 i178132955

**Comment by xinyu198736** [comment]
你好，直接打款到 xinyu198736@gmail.com 哈，账号姓名：孙信宇

**Comment by xinyu198736** [comment]
感谢支持，已经收款
 ![](https://github.com/Hangzhou-Node-Party/JS-OpenSource-Foundation/raw/master/img/donate-32.jpeg)
