### ISSUE TITLE
Apply Income: 20180626 第六期NodeParty门票收入 7226.40¥

### ISSUE THREAD

**Issue by yuzhigang33** [Hangzhou-Node-Party/Node-OpenSource-Foundation#54]

**Comment by yuzhigang33** [comment]
钱已转入基金会账号
![wechatimg67](https://user-images.githubusercontent.com/929503/41972778-761db5bc-7a45-11e8-974b-6274502b613d.jpeg)

**Comment by xinyu198736** [comment]
已收到
