### ISSUE TITLE
present donate: 20180826 个人名义赞助 1000元

### ISSUE THREAD

**Issue by xudafeng** [Hangzhou-Node-Party/Node-OpenSource-Foundation#57]
普及 Node.js 技术，让跟多人学到知识，希望 NodeParty 能一直办下去。

**Comment by xudafeng** [comment]
****
![image](https://user-images.githubusercontent.com/1011681/44659204-f8441480-aa35-11e8-9ede-4b54b396cb65.png)

**Comment by xudafeng** [comment]
@xinyu198736

**Comment by xudafeng** [comment]
https://github.com/Hangzhou-Node-Party/Node-OpenSource-Foundation/pull/58

**Comment by xinyu198736** [comment]
已收到，并更新记录，感谢支持！
